import type { Transaction } from '@/lib/actions/transactions'

// Datos de demo que coinciden con la interfaz Transaction
export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-1',
    accountId: 'demo-acc-1',
    accountName: 'Cuenta Corriente',
    categoryId: 'demo-cat-1',
    categoryName: 'Ventas',
    type: 'income',
    status: 'posted',
    amount: 2500000,
    currency: 'COP',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    description: 'Venta de software a cliente corporativo',
    createdAt: new Date().toISOString(),
    createdBy: 'demo-user-001',
    creatorName: 'Usuario Demo',
  },
  {
    id: 'demo-2',
    accountId: 'demo-acc-1',
    accountName: 'Cuenta Corriente',
    categoryId: 'demo-cat-2',
    categoryName: 'Nómina',
    type: 'expense',
    status: 'approved',
    amount: 1500000,
    currency: 'COP',
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
    description: 'Pago de nómina mensual',
    createdAt: new Date().toISOString(),
    createdBy: 'demo-user-001',
    creatorName: 'Usuario Demo',
  },
  {
    id: 'demo-3',
    accountId: 'demo-acc-2',
    accountName: 'Ahorros',
    categoryId: 'demo-cat-1',
    categoryName: 'Servicios',
    type: 'income',
    status: 'pending',
    amount: 800000,
    currency: 'COP',
    date: new Date(Date.now() - 86400000).toISOString(),
    description: 'Servicios de consultoría',
    createdAt: new Date().toISOString(),
    createdBy: 'demo-user-001',
    creatorName: 'Usuario Demo',
  },
  {
    id: 'demo-4',
    accountId: 'demo-acc-3',
    accountName: 'Efectivo',
    categoryId: 'demo-cat-3',
    categoryName: 'Insumos',
    type: 'expense',
    status: 'draft',
    amount: 500000,
    currency: 'COP',
    date: new Date().toISOString(),
    description: 'Compra de insumos de oficina',
    createdAt: new Date().toISOString(),
    createdBy: 'demo-user-001',
    creatorName: 'Usuario Demo',
  },
  {
    id: 'demo-5',
    accountId: 'demo-acc-1',
    accountName: 'Cuenta Corriente',
    categoryId: null,
    categoryName: null,
    type: 'transfer',
    status: 'posted',
    amount: 1000000,
    currency: 'COP',
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    description: 'Transferencia entre cuentas',
    createdAt: new Date().toISOString(),
    createdBy: 'demo-user-001',
    creatorName: 'Usuario Demo',
  },
]

export const DEMO_STATS = {
  totalTransactions: DEMO_TRANSACTIONS.length,
  pendingCount: DEMO_TRANSACTIONS.filter(t => t.status === 'pending').length,
  approvedCount: DEMO_TRANSACTIONS.filter(t => t.status === 'approved').length,
  postedCount: DEMO_TRANSACTIONS.filter(t => t.status === 'posted').length,
  totalIncome: DEMO_TRANSACTIONS
    .filter(t => t.type === 'income' && t.status === 'posted')
    .reduce((sum, t) => sum + t.amount, 0),
  totalExpenses: DEMO_TRANSACTIONS
    .filter(t => t.type === 'expense' && t.status === 'posted')
    .reduce((sum, t) => sum + t.amount, 0),
}
